version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: hw3-postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: mikaeloganesan
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hw3-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: hw3-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - hw3-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: hw3-kafka
    depends_on:
      - zookeeper
    ports:
      - "29093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hw3-net

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: hw3-kafka-init
    depends_on:
      - kafka
    entrypoint:
      - /bin/sh
      - -c
      - |
        cub kafka-ready -b kafka:9092 1 20
        kafka-topics --create --topic orders --bootstrap-server kafka:9092 || true
        kafka-topics --create --topic payment-status --bootstrap-server kafka:9092 || true
        tail -f /dev/null
    networks:
      - hw3-net

  payments-service:
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    container_name: hw3-payments-service
    depends_on:
      - postgres
      - kafka
    environment:
      - DATABASE_URL=postgres://mikaeloganesan:password@postgres:5432/payments?sslmode=disable
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8080:8080"
    networks:
      - hw3-net

  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: hw3-orders-service
    depends_on:
      - postgres
      - kafka
    environment:
      - DATABASE_URL=postgres://mikaeloganesan:password@postgres:5432/payments?sslmode=disable
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8081:8081"
    networks:
      - hw3-net

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: hw3-gateway
    depends_on:
      - payments-service
      - orders-service
    ports:
      - "3000:3000"
    environment:
      - PAYMENTS_SERVICE_URL=http://payments-service:8080
      - ORDERS_SERVICE_URL=http://orders-service:8081
    networks:
      - hw3-net

volumes:
  pgdata:

networks:
  hw3-net:
    driver: bridge
