basePath: /
definitions:
  models.Order:
    properties:
      amount:
        type: integer
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        type: string
      updatedAt:
        type: string
      userID:
        type: string
    type: object
  models.Outbox:
    properties:
      createdAt:
        type: string
      eventType:
        type: string
      id:
        type: string
      payload:
        items:
          type: integer
        type: array
      sent:
        type: boolean
    type: object
host: localhost:8081
info:
  contact: {}
  description: API для управления заказами
  title: Orders Service API
  version: "1.0"
paths:
  /orders:
    get:
      description: Возвращает список всех заказов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить список заказов
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Создает новый заказ и ставит в очередь
      parameters:
      - description: Данные заказа
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.Outbox'
      produces:
      - application/json
      responses:
        "202":
          description: Order accepted
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать заказ
      tags:
      - orders
  /orders/{id}/status:
    get:
      description: Возвращает статус заказа по ID
      parameters:
      - description: ID заказа
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Order not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить статус заказа
      tags:
      - orders
swagger: "2.0"
